
volumes:
  kingsley-db

services:
  mongodb:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: kingsley
      TZ: America/Chicago
    volumes: kingsley-db:/data/db
    ports:
      - 27017:27017